"""base revision

Establishes the initial (empty) migration baseline for the Pipeline_UI backend.
The concrete domain models arrive in task 2.1; the first autogenerated
migration that creates the domain tables will chain off this base revision
(``down_revision = "0001"``).

Revision ID: 0001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from __future__ import annotations

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Intentionally empty: this is the baseline. Domain tables are added by the
    # migration generated in task 2.2 against Base.metadata.
    pass


def downgrade() -> None:
    pass
