"""criar tabelas do dominio

Migração inicial do domínio (task 2.2). Cria as 9 tabelas do domínio
(``casos``, ``execucoes_estagio``, ``abilities``, ``adversaries``,
``operacoes``, ``resultados_ability``, ``auditoria``, ``estado_sessao``,
``preferencias``), encadeada sobre a revisão base ``0001``.

Notas de revisão (autogerado + revisado — _Requisitos: 9.1_):

* Tipos portáveis apenas (``String``, ``Text``, ``Integer``, ``DateTime``,
  ``JSON``); nenhum tipo específico de backend. Funciona igual em SQLite (dev)
  e PostgreSQL (produção).
* Enums persistem como ``VARCHAR`` portável via ``native_enum=False``,
  reproduzindo fielmente os modelos da task 2.1 (``sa.Enum(..., native_enum=
  False)``). ``alembic check`` confirma ausência de drift contra
  ``Base.metadata``.
* Campos NOT NULL de ``AuditLogEntry`` preservados: ``comando``,
  ``container_destino`` e ``registrado_em`` (Req. 6.8).
* Ordem de criação respeita as chaves estrangeiras (``casos`` antes das
  tabelas que a referenciam; ``operacoes`` antes de ``auditoria`` e
  ``resultados_ability``); o ``downgrade`` inverte a ordem.
* Colunas JSON: ``abilities.executors`` e ``adversaries.atomic_ordering``.

Verificado em SQLite: ``upgrade head`` cria as 9 tabelas, ``downgrade base``
reverte sem resíduos e ``alembic check`` não detecta operações novas.

Revision ID: a28d8c1ae4aa
Revises: 0001
Create Date: 2026-09-27 20:54:39.226790+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a28d8c1ae4aa'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('casos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('arquivo_ability', sa.String(), nullable=True),
    sa.Column('arquivo_adversary', sa.String(), nullable=True),
    sa.Column('arquivo_dag', sa.String(), nullable=True),
    sa.Column('origem_traducao', sa.Enum('curadoria_humana', name='translation_source', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tema', sa.Enum('claro', 'escuro', name='theme', native_enum=False), nullable=False),
    sa.Column('idioma', sa.Enum('pt-BR', 'en', name='language', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abilities',
    sa.Column('ability_id', sa.String(), nullable=False),
    sa.Column('caso_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('tactic', sa.String(), nullable=True),
    sa.Column('technique_name', sa.String(), nullable=True),
    sa.Column('technique_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('executors', sa.JSON(), nullable=True),
    sa.Column('origem_traducao', sa.Enum('curadoria_humana', name='translation_source', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('ability_id')
    )
    op.create_table('adversaries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('caso_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('atomic_ordering', sa.JSON(), nullable=True),
    sa.Column('origem_traducao', sa.Enum('curadoria_humana', name='translation_source', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estado_sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_atual', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_atual'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execucoes_estagio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.String(), nullable=True),
    sa.Column('estagio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('nao_iniciado', 'em_andamento', 'concluido', 'erro', name='stage_state', native_enum=False), nullable=False),
    sa.Column('progresso', sa.Integer(), nullable=False),
    sa.Column('mensagem_erro', sa.Text(), nullable=True),
    sa.Column('etapa_falha', sa.String(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('caso_id', sa.String(), nullable=True),
    sa.Column('caldera_operation_id', sa.String(), nullable=True),
    sa.Column('estado', sa.Enum('nao_iniciada', 'em_execucao', 'finalizada', 'abortada', name='operation_state', native_enum=False), nullable=False),
    sa.Column('total_sucesso', sa.Integer(), nullable=False),
    sa.Column('total_falha', sa.Integer(), nullable=False),
    sa.Column('iniciada_em', sa.DateTime(), nullable=True),
    sa.Column('finalizada_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['caso_id'], ['casos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.String(), nullable=True),
    sa.Column('comando', sa.Text(), nullable=False),
    sa.Column('container_destino', sa.String(), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('registrado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=True),
    sa.Column('ability_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'em_execucao', 'sucesso', 'falha', name='ability_result_status', native_enum=False), nullable=False),
    sa.Column('saida_comando', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['abilities.ability_id'], ),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_ability')
    op.drop_table('auditoria')
    op.drop_table('operacoes')
    op.drop_table('execucoes_estagio')
    op.drop_table('estado_sessao')
    op.drop_table('adversaries')
    op.drop_table('abilities')
    op.drop_table('preferencias')
    op.drop_table('casos')
    # ### end Alembic commands ###
